name: "Push path to OCI Registry"
author: Eliran Bivas
branding:
  icon: arrow-up-circle
  color: blue
description: "Push a specified path to an OCI registry if a specific path changes"
inputs:
  path:
    description: "The path to push to the OCI registry"
    required: true
  image_repository:
    description: "The repository of the OCI image"
    required: true
  oci_registry:
    description: "The OCI registry to push the image to"
    required: true
  registry_username:
    description: "The username for the OCI registry"
    required: true
  registry_password:
    description: "The password for the OCI registry"
    required: true
outputs:
  image_full_name:
    description: "The full name of the OCI image"
    value: ${{ steps.push-image.outputs.full-image-name }}
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        sparse-checkout: ${{ inputs.path }}

    - uses: oras-project/setup-oras@v1
    - run: |
        IMAGE_NAME="${{ inputs.oci_registry }}/${{ inputs.image_repository }}:$(git rev-parse HEAD)"
        echo "full-image-name=$(echo $IMAGE_NAME)" >> $GITHUB_OUTPUT
        oras login --username ${{ inputs.registry_username }} --password ${{ inputs.registry_password }} ${{ inputs.oci_registry }}
        oras push ${IMAGE_NAME} ${{ inputs.path }}
      shell: bash
      id: push-image
